### ISSUE TITLE
Improve Localization Support

### ISSUE THREAD

**Issue by Dontknow09** [FoundryMC/Veil#10]
I really want to translate the text objects that make up the Editor but most of them are string literals instead of translatable strings.

Could we perhaps fix this to allow for Localization of this library?

(I could probably try to fix this myself but then I would need help compiling the mod since I don't have a proper dev env set up right now)

**Comment by IDoTheHax** [comment]
I could do It

**Comment by IDoTheHax** [comment]
shat beat me to it, ig ill do dutch and german translations then
