### ISSUE TITLE
[Fabric 1.20.1, Veil 1.0.0.256] StackOverflowError error when starting the game

### ISSUE THREAD

**Issue by JakeSmythUK** [FoundryMC/Veil#15]
I'm getting a `StackOverflowError` just as the game is about to render the startup logo. I'm running Veil `1.0.0.256` and it's caused by the method at `net.minecraft.client.util.math.MatrixStack.push`.
Trying to breakpoint it sends me to the `foundry.veil.mixin.client.pipeline.PoseStackMixin` class so the issue is probably something there.

I'm running Windows 10 with a GTX 1050 Ti. In a dev environment using no other mods apart from this one as a dependency.

A similar issue was resolved in [Issue #13](https://github.com/FoundryMC/Veil/issues/13). Might be useful for troubleshooting this.

**Comment by briarss** [comment]
Update veil to the latest version.

**Comment by JakeSmythUK** [comment]
> Update veil to the latest version.

To my knowledge, `1.0.0.256` is the latest version as it was released today but if I'm missing something please let me know.

**Comment by briarss** [comment]
Hm odd, this was fixed. This is caused by Yarn mappings iirc - if you're able to move off of Yarn it should fix things.

Edit: Until we can confirm why its broken again, that is.

**Comment by JakeSmythUK** [comment]
Yea I've been using Yarn. I'll have a see how Mojmap feels while it's figured out! Thanks!
