### ISSUE TITLE
Clipboard bug

### ISSUE THREAD

**Issue by Xyndra** [FoundryMC/Veil#18]
This gets spammed every now and then in the editor
```
[21:16:55] [Render thread/ERROR] (Minecraft) ########## GL ERROR ##########
[21:16:55] [Render thread/ERROR] (Minecraft) @ Render
[21:16:55] [Render thread/ERROR] (Minecraft) 65545: Win32: Failed to convert clipboard to string: Element nicht gefunden.
```

This should probably be handled without GL Error

**Comment by lars2800** [comment]
I get that too it just spams it idk know why tho.

**Comment by Xyndra** [comment]
it is because something other than text is in the clipboard

**Comment by lars2800** [comment]
Why does OpenGl care about that?

**Comment by lars2800** [comment]
I think it might be handeld via opengl thread or somthing

**Comment by Xyndra** [comment]
It is not actually a GL error but it probably occurs in the same try catch block. It seems to happen when calling native windows API to give the clipboard text but it isn't actually text so it errors

**Comment by Xyndra** [comment]
![image](https://github.com/user-attachments/assets/1f985928-eb7e-44a2-acca-de15e2b9e8c5)
Just saw this line in vanilla MC under client/keyboard
