### ISSUE TITLE
[1.20.4, Fabric] Mixin error on load

### ISSUE THREAD

**Issue by BeefyAndTheDucks** [FoundryMC/Veil#2]
When starting the game I get the following error:
`Mixin transformation of net.minecraft.client.render.WorldRenderer failed`
Crash log:
"---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2024-04-17 18:51:59
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'veil'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.render.WorldRenderer failed
	at foundry.veil.fabric.event.FabricVeilRenderLevelStageEvent.lambda$static$1(FabricVeilRenderLevelStageEvent.java:17)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:54)
	at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:50)
	at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:47)
	at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:44)
	at foundry.veil.fabric.event.FabricVeilRenderLevelStageEvent.<clinit>(FabricVeilRenderLevelStageEvent.java:17)
	at foundry.veil.fabric.FabricQuasarParticleHandler.init(FabricQuasarParticleHandler.java:31)
	at foundry.veil.fabric.VeilFabricClient.onInitializeClient(VeilFabricClient.java:55)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.client.render.WorldRenderer failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/client/render/WorldRenderer::render(Lnet/minecraft/client/util/math/MatrixStack;FJZLnet/minecraft/client/render/Camera;Lnet/minecraft/client/render/GameRenderer;Lnet/minecraft/client/render/LightmapTextureManager;Lorg/joml/Matrix4f;)V has incompatible changes at opcode 302 in callback veil.fabric.mixins.json:client.stage.LevelRendererMixin from mod veil->@Inject::postRenderSky(Lnet/minecraft/client/util/math/MatrixStack;FJZLnet/minecraft/client/render/Camera;Lnet/minecraft/client/render/GameRenderer;Lnet/minecraft/client/render/LightmapTextureManager;Lorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/util/profiler/Profiler;Lnet/minecraft/util/math/Vec3d;DDDLorg/joml/Matrix4f;ZLnet/minecraft/client/render/Frustum;)V.
 Expected: [Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;, Z, Lnet/minecraft/client/render/Frustum;]
    Found: [Lnet/minecraft/world/tick/TickManager;, F, Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;]
Available: [Lnet/minecraft/world/tick/TickManager;, F, Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;, Z, Lnet/minecraft/client/render/Frustum;, F, Z]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:544)
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:494)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:277)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1377)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:487)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		aswAMSI.dll:Avast AMSI COM object:24.3.8975.0:Gen Digital Inc.
		aswhook.dll:Avast Hook Library:24.3.8975.0:AVAST Software
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		iertutil.dll:Run time utility for Internet Explorer:11.00.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		java.exe:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		jna1009197213496577195.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.7.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		netutils.dll:Net Win32 API Helpers DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		srvcli.dll:Server Service Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		urlmon.dll:OLE32 Extensions for Win32:11.00.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.31.31103.0:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
		win32u.dll:Win32u:10.0.22621.3447 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.2860 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.7.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.7, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 115995104 bytes (110 MiB) / 423624704 bytes (404 MiB) up to 2107637760 bytes (2010 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Meta Virtual Monitor
	Graphics card #0 vendor: Meta Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=17.12.55.198
	Graphics card #1 name: Intel(R) UHD Graphics 630
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3e9b
	Graphics card #1 versionInfo: DriverVersion=27.20.100.8935
	Graphics card #2 name: NVIDIA GeForce GTX 1650
	Graphics card #2 vendor: NVIDIA (0x10de)
	Graphics card #2 VRAM (MB): 4095.00
	Graphics card #2 deviceId: 0x1f91
	Graphics card #2 versionInfo: DriverVersion=31.0.15.5176
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30582.87
	Virtual memory used (MB): 25808.25
	Swap memory total (MB): 22546.05
	Swap memory used (MB): 4017.44
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.97.0+1.20.4
		fabric-api-base: Fabric API Base 0.4.37+78d798af4f
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
		fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
		fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
		fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
		fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
		fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
		fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
		fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
		fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
		fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
		fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
		fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
		fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
		fabric-gametest-api-v1: Fabric Game Test API (v1) 1.3.6+85d85a934f
		fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
		fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
		fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
		fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
		fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
		fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
		fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
		fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
		fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
		fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
		fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
		fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
		fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
		fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
		fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabricloader: Fabric Loader 0.15.10
		jankson: Jankson 6.0.0+j1.2.3
		java: Java HotSpot(TM) 64-Bit Server VM 17
		libgui: LibGui 9.2.2+1.20.2
		libninepatch: LibNinePatch 1.2.0
		minecraft: Minecraft 1.20.4
		mixinextras: MixinExtras 0.3.5
		modmenu: Mod Menu 9.0.0
		spacecraft: SpaceCraft 0.1.0.0-1.20.4
		terrablender: TerraBlender 3.3.0.12
		veil: Veil 1.0.0
	Launched Version: Fabric
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>"
Also, before the crash I get a 
`Critical injection failure: LVT in net/minecraft/client/render/WorldRenderer::render(Lnet/minecraft/client/util/math/MatrixStack;FJZLnet/minecraft/client/render/Camera;Lnet/minecraft/client/render/GameRenderer;Lnet/minecraft/client/render/LightmapTextureManager;Lorg/joml/Matrix4f;)V has incompatible changes at opcode 302 in callback veil.fabric.mixins.json:client.stage.LevelRendererMixin from mod veil->@Inject::postRenderSky(Lnet/minecraft/client/util/math/MatrixStack;FJZLnet/minecraft/client/render/Camera;Lnet/minecraft/client/render/GameRenderer;Lnet/minecraft/client/render/LightmapTextureManager;Lorg/joml/Matrix4f;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/util/profiler/Profiler;Lnet/minecraft/util/math/Vec3d;DDDLorg/joml/Matrix4f;ZLnet/minecraft/client/render/Frustum;)V.
 Expected: [Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;, Z, Lnet/minecraft/client/render/Frustum;]
    Found: [Lnet/minecraft/world/tick/TickManager;, F, Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;]
Available: [Lnet/minecraft/world/tick/TickManager;, F, Lnet/minecraft/util/profiler/Profiler;, Lnet/minecraft/util/math/Vec3d;, D, D, D, Lorg/joml/Matrix4f;, Z, Lnet/minecraft/client/render/Frustum;, F, Z]`.

Also, here are my gradle modImplementations:
`repositories {
    maven {
        name = 'BlameJared Maven (CrT / Bookshelf)'
        url = 'https://maven.blamejared.com'
    }
}`
and
`dependencies {
    modImplementation("foundry.veil:Veil-fabric-${project.minecraft_version}:${project.veil_version}") { transitive = false }
    modImplementation("foundry.veil:Veil-common-${project.minecraft_version}:${project.veil_version}") { transitive = false }
}`.
Thanks in advance.

**Comment by Underplayer97** [comment]
Can confirm having same issues on 1.0.0.42 and 1.0.0.37, switched to 1.20.1 for now and worked. It just seems that 1.20.4 is having issues with WorldRenderer
