### ISSUE TITLE
Cannot enable light renderer

### ISSUE THREAD

**Issue by philipprhrd** [FoundryMC/Veil#33]
**Description**
Hi, I would like to use the light editor for some testing. I figured out that I need to enable the DeferredRenderer but I don't know how to enable it.

**System Information**
Please provide the following information:
- **Veil Version**:  1.0.0.43
- **Minecraft Version**: 1.20.4
- **Loader & Loader Version**: Fabric 0.15.11
- **Operating System**: Windows 10

**Comment by briarss** [comment]
Enable the deferred renderer resourcepack and then F3+T

**Comment by philipprhrd** [comment]
Alright done. But the ImGui Menu Option is grayed out but in the console it says that the deferred renderer is active.

Do I need to refresh the ImGui? Thanks for you help. Is there a discord where I can write my questions?

**Comment by briarss** [comment]
F3+T and it should enable.

**Comment by MonsPropre** [comment]
anyway to enable the defered pack by default because don't want the player have to enable a texture pack as it is a mod :/
