### ISSUE TITLE
Request for Better Documentation and Examples for Quasar Particle System

### ISSUE THREAD

**Issue by philipprhrd** [FoundryMC/Veil#35]
As a new user trying to implement the Quasar particle system, I've found it difficult to get started due to its unique approach. Clear documentation and examples would significantly reduce the learning curve and make it easier for developers to integrate this powerful tool into their projects.

**Describe the solution you'd like**
I would greatly appreciate:
1. Documentation for the Quasar particle system
2. A set of well-explained, easy-to-understand examples demonstrating various use cases

Thank you for considering this request.

**Comment by briarss** [comment]
This is already sort of wip, there's a community-made one somewhere too (@Redfan2 i think?) but there'll be a lot more docu and stuff come 1.21
