### ISSUE TITLE
What is the location for post processing shades?

### ISSUE THREAD

**Issue by lars2800** [FoundryMC/Veil#41]
**Question**
I have my post processing json like this:
![image](https://github.com/user-attachments/assets/15cf0ee8-8885-4e52-99e3-5f7afa2a0bc1)

Where do i put this file so that the post processing shader loads?

Also does anyone know if there is some discord / forum where i can ask these kind of questions?

**Comment by Redfan2** [comment]
In terms of the path, you can look at how Veil does it here: https://github.com/FoundryMC/Veil/tree/1.20/common/src/main/resources/resourcepacks/test_shaders/assets/veil/pinwheel/post
Also, yes they have a Discord: https://discord.gg/2aqTX9QWKU

**Comment by lars2800** [comment]
Thank you
