### ISSUE TITLE
Deferred renderer completely broken [Minecraft 1.20.1, Veil 1.0.0.229]

### ISSUE THREAD

**Issue by NikkiOfTheValley** [FoundryMC/Veil#8]
I tried to enable the deferred renderer, which seems to have completely broken every single shader in the game. The root cause seems to be that all `#define` directives are broken. All of them give a syntax error in this format: `'[NAME] : undeclared identifier`. I do not have the foggiest clue why that's happening, otherwise I'd have fixed it for you.

**Comment by briarss** [comment]
What OS are you on? What other mods do you have installed? Need more info.

**Comment by Ocelot5836** [comment]
Fixed in 4d2e3f5
