### ISSUE TITLE
custom entity shader?

### ISSUE THREAD

**Issue by MHanak1** [FoundryMC/Veil#9]
i am trying to create an entity with a custom shader (so it would appear as a sphere). How would i approach doing that?

(as a little disclaimer i have no idea what i am doing, i just started using this library, and i am still a beginner when it comes to mc modding)

**Comment by MHanak1** [comment]
so i've just realised that in the example project you are using blockentities, so i might be able to adapt that code

also is this one mixin in the example _really_ nessesary?

**Comment by briarss** [comment]
This isnt really the place to be asking for development help, we have a help channel in the discord.

**Comment by MHanak1** [comment]
> This isnt really the place to be asking for development help, we have a help channel in the discord.

I see, could you please link the discord server? i could not find it anywhere

**Comment by briarss** [comment]
https://discord.gg/2aqTX9QWKU
